# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: fadeit /blog - development and design articles for all you console cowboys
email: info@fadeit.dk
description: > # this means to ignore newlines until "baseurl:"
  Our blog is a great place to find tech-related articles & tutorials to kick-start your next project. We love to share our knowledge and help others learn from our experience both in development and design.
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://fadeit.dk" # the base hostname & protocol for your site
twitter_username: fadeitdk
github_username:  fadeit
google_analytics_code: UA-47022100-1
permalink: pretty
markdown: kramdown
highlighter: rouge

# More › http://kramdown.gettalong.org/quickref.html
# Options › http://kramdown.gettalong.org/options.html
kramdown:
  input: GFM
  # https://github.com/jekyll/jekyll/pull/4090
  syntax_highlighter: rouge

  # Rouge Highlighter in Kramdown › http://kramdown.gettalong.org/syntax_highlighter/rouge.html
  syntax_highlighter_opts:
    # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: 'highlight'

gems:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - node_modules
  - package.json
  - package.json
  - README.md
  - Gemfile
  - Gemfile.lock

paginate: 10
paginate_path: "/:num/"

# Post defaults
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
      size: 12
      sizeDesktop: 12
      textColor: "grey-50"
      metaColor: "grey-600"
      image: "https://fadeit.dk/src/assets/img/brand/fadeit_logo_square.png"


authors:
  dan:
    display_name: "Dan Mindru"
    title: "Front-end developer"
    gravatar: "37131e747ce8855b4015024d64668e7d"
    email: "dm@fadeit.dk"
    web: "http://mindrudan.com/"
    twitter: "d4m1n"
    github: "danmindru"
  justas:
    display_name: "Justas Azna"
    title: "Software engineer"
    gravatar: "3b506312d288ba78253aef2222fcfb78"
    email: "ja@fadeit.dk"
    web: "http://reederz.com/"
    twitter: "reederz"
    github: "reederz"
  sander:
    display_name: "Sander Sink"
    title: "Software engineer"
    gravatar: "3b506312d288ba78253aef2222fcfb78" # Actually Justas' gravatar
    email: "ss@fadeit.dk"
    github: "ozooner"
  fadeit:
    display_name: "fadeit"
    title: "Software development company"
    gravatar: "3b506312d288ba78253aef2222fcfb78"
    email: "info@fadeit.dk"
    web: "http://fadeit.dk/"
    twitter: "fadeitdk"
    github: "fadeit"
