encoding: utf-8
# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Vue.js rocks! Vue components, plugins, tutorials and more!
email: info@fadeit.dk
description: > # this means to ignore newlines until "baseurl:"
  The Vue.js rocks blog is a great place to learn new things about Vue.js components, plugins, build tools and everything in between.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://vue.rocks" # the base hostname & protocol for your site
twitter_username: vuerocks
github_username:  vuerocks
google_analytics_code: UA-29019414-14
permalink: pretty
markdown: kramdown
highlighter: rouge

# More › http://kramdown.gettalong.org/quickref.html
# Options › http://kramdown.gettalong.org/options.html
kramdown:
  input: GFM
  # https://github.com/jekyll/jekyll/pull/4090
  syntax_highlighter: rouge

  # Rouge Highlighter in Kramdown › http://kramdown.gettalong.org/syntax_highlighter/rouge.html
  syntax_highlighter_opts:
    # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: 'highlight'

gems:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-assets

exclude:
  - node_modules
  - package.json
  - README.md
  - Gemfile
  - Gemfile.lock

assets:
  autoprefixer:
    compress:
      css: true
      js: true

    browsers:
      - "last 3 versions"

tag_page_layout: tag_page
tag_page_dir: tag

tag_feed_layout: tag_feed
tag_feed_dir: tag_atom

paginate: 10
paginate_path: "/:num/"

ampdir: "amp/"

# Post defaults
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
      size: 12
      sizeDesktop: 12
      textColor: "grey-50"
      metaColor: "grey-600"
      image: "https://cloud.githubusercontent.com/assets/1515742/21673828/83e96246-d333-11e6-8b05-561cbd757c4f.png"


authors:
  dan:
    display_name: "Dan Mindru"
    title: "Front-end developer"
    gravatar: "37131e747ce8855b4015024d64668e7d"
    email: "dm@fadeit.dk"
    web: "http://mindrudan.com/"
    twitter: "d4m1n"
    github: "danmindru"
