source 'http://rubygems.org'
gem "jekyll-assets"
gem "jekyll-paginate"
gem "jekyll-seo-tag"
gem "jekyll-sitemap"
gem 'jekyll-tagging'
gem "jekyll-watch"
gem "autoprefixer-rails"
gem "kramdown"
gem "rouge"
